# Generated by Django 3.2.8 on 2021-10-29 01:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=200)),
                ('group_size', models.PositiveIntegerField(default=0)),
                ('group_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=40)),
                ('password', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('register_date', models.DateTimeField(verbose_name='date of registration')),
                ('organizations', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='annotations.organization')),
            ],
        ),
        migrations.AddField(
            model_name='organization',
            name='supervisor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='annotations.user'),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(max_length=200)),
                ('submission_date', models.DateTimeField(verbose_name='date of submission')),
                ('svs_path', models.FilePathField(max_length=200)),
                ('dzi_path', models.FilePathField(max_length=200)),
                ('height', models.PositiveIntegerField()),
                ('width', models.PositiveIntegerField()),
                ('image_description', models.TextField()),
                ('completely_annotated', models.BooleanField(default='False')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='annotations.imagegroup')),
                ('submit_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='annotations.user')),
            ],
        ),
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contour', models.JSONField()),
                ('update_date', models.DateTimeField(verbose_name='date submit this annotation')),
                ('annotator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='annotations.user')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annotations.image')),
            ],
        ),
    ]
