# Generated by Django 3.2.8 on 2021-10-29 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='dzi_path',
            field=models.FilePathField(match='*.dzi', path='~/dzis'),
        ),
        migrations.AlterField(
            model_name='image',
            name='svs_path',
            field=models.FilePathField(match='*.svs', path='~/svss'),
        ),
    ]
