# Generated by Django 3.2.8 on 2021-10-29 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0002_auto_20211029_0304'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='UNI',
            field=models.CharField(default='yl4326', max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='legal_name',
            field=models.CharField(default='Yihao Li', max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='image',
            name='dzi_path',
            field=models.FilePathField(match='*\\.dzi', path='~/dzis'),
        ),
        migrations.AlterField(
            model_name='image',
            name='svs_path',
            field=models.FilePathField(match='*\\.svs', path='~/svss'),
        ),
    ]
