# Generated by Django 3.2.8 on 2021-11-02 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0003_image_image_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='translated',
            field=models.BooleanField(default='False'),
        ),
        migrations.AlterField(
            model_name='image',
            name='submit_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='annotations.user'),
        ),
    ]
