# Generated by Django 3.2.8 on 2021-11-02 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0004_auto_20211102_1819'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagegroup',
            name='group_size',
        ),
        migrations.AlterField(
            model_name='image',
            name='image_name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='imagegroup',
            name='group_name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='organization_name',
            field=models.CharField(max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='UNI',
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
