# Generated by Django 3.2.8 on 2021-10-30 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0004_auto_20211029_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='dzi_path',
            field=models.FilePathField(match='.*\\.dzi', path='/home/alexliyihao/dzis'),
        ),
        migrations.AlterField(
            model_name='image',
            name='svs_path',
            field=models.FilePathField(match='.*\\.svs', path='/home/alexliyihao/svss'),
        ),
    ]
