# Generated by Django 3.2.8 on 2021-11-03 03:04

import annotations.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0005_auto_20211102_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_upload',
            field=models.FileField(upload_to=annotations.models.svs_rename),
        ),
    ]
