# Generated by Django 3.2.8 on 2021-11-08 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0007_auto_20211107_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotation',
            name='contour',
            field=models.JSONField(blank=True),
        ),
    ]
