# Generated by Django 3.2.8 on 2021-11-09 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0008_alter_annotation_contour'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='W3C_id',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
