# Generated by Django 3.2.8 on 2021-11-09 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0011_auto_20211108_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='dzi_path',
            field=models.FilePathField(blank=True, match='.*\\.dzi', null=True, path='/home/alexliyihao/dzis'),
        ),
        migrations.AlterField(
            model_name='image',
            name='svs_path',
            field=models.FilePathField(blank=True, match='.*\\.svs', null=True, path='/home/alexliyihao/svss'),
        ),
    ]
