# Generated by Django 3.2.8 on 2021-11-11 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0013_auto_20211109_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotation',
            name='annotation_class',
            field=models.CharField(blank=True, choices=[('Glomerulus', 'Glomerulus'), ('Arteries', 'Arteries'), ('Tubules', 'Tubules'), ('Interstitium', 'Interstitium'), ('Undecided', 'Undecided')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='update_date',
            field=models.DateTimeField(auto_now=True, verbose_name='date submit this annotation'),
        ),
        migrations.AlterField(
            model_name='image',
            name='submission_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date of submission'),
        ),
        migrations.AlterField(
            model_name='imagegroup',
            name='group_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='imagegroup',
            name='group_name',
            field=models.CharField(max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='register_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date of registration'),
        ),
    ]
