# Generated by Django 3.2.8 on 2021-11-11 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0014_auto_20211110_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='description',
            field=models.CharField(default='test description', max_length=400),
            preserve_default=False,
        ),
    ]
