# Generated by Django 3.2.8 on 2021-11-11 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0015_organization_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
