# Generated by Django 3.2.8 on 2021-11-18 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0016_alter_organization_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotation',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='image_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
